### PR TITLE
Fix project deployment and increment npm version

### PR DESCRIPTION
**Pull request by clems4ever**

### CODE REVIEW

**Comment by rmdort** [comment]
Getting a new error when i start the chatbot after this update

```
 project will restart on model changes.
module.js:328
    throw err;
    ^

Error: Cannot find module './open-intent.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/XXX/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/chatbot-factory.js:40:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by clems4ever** [comment]
What is your version of open-intent? Is it the latest, v1.0.18?

**Comment by rmdort** [comment]
Yes. I am using v1.0.18 on node 4.2.6 and npm 3.10.8

**Comment by clems4ever** [comment]
Hello @rmdort , it should be solved with version v1.0.19. The **open-intent.node** file was in the .gitignore and thus not published in the npm repository. Please try again now.

**Comment by rmdort** [comment]
hmm.. I am getting this error

```
Starting: /Users/XXX/Sites/mychatbot/app.js...
  project will restart on model changes.
module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/XXX/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/open-intent.node, 1): no suitable image found.  Did find:
        /Users/vinay/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/open-intent.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXX/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/chatbot-factory.js:40:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

Am i doing something wrong?  What i am doing i s

```
npm install -g open-intent
open-intent project create mychatbot
open-intent project start mychatbot
```

The version is 1.0.19

**Comment by clems4ever** [comment]
hello @rmdort,  are you working on Linux? Which distro? 
It seems that the C++ node plugin cannot be executed. We compiled it on ubuntu 16.04.

**Comment by rmdort** [comment]
I am on Mac OS Sierra.

**Comment by clems4ever** [comment]
OMG. I'm so sorry I did not noticed you were using Mac before. This is not highlighted in the doc but we currently support Linux only. I will emphasize it right away in the doc. However we work on making the other platforms available but for now the only solution to test with those platforms is docker. I'm really sorry @rmdort.

**Pull request merged**
